version: '2.1'

services:

  user-shell:
    build:
      context: .
      dockerfile: ./shell/users/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-user-shell
    container_name: user-shell
    volumes:
      - .:/project/sawtooth-user
      - /project/sawtooth-user/client/node_modules
    command: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
          sawtooth keygen
        fi;
        cd client
        npm run-script build
        cd ../
        tail -f /dev/null
      "

  user-client:
    build: ./client
    image: sawtooth-user-client
    container_name: user-client
    volumes:
      - ./client/:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8000:80'
    depends_on:
    - rest-api
    - user-shell
    - cars-shell
    - invitations-shell

  user-tp:
    build:
      context: .
      dockerfile: ./processor/user_tp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-user-tp
    container_name: user-tp
    volumes:
      - '.:/project/sawtooth-user'
    depends_on:
      - user-shell
    command: |
      bash -c "
        sleep 1
        user-tp -vv -C tcp://validator:4004
      "

  cars-shell:
    build:
      context: .
      dockerfile: ./shell/cars/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-cars-shell
    container_name: cars-shell
    volumes:
      - .:/project/sawtooth-cars
      - /project/sawtooth-cars/client/node_modules
    command: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
          sawtooth keygen
        fi;
        cd client
        npm run-script build
        cd ../
        tail -f /dev/null
      "

  cars-tp:
    build:
      context: .
      dockerfile: ./processor/cars_tp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-cars-tp
    container_name: cars-tp
    volumes:
      - '.:/project/sawtooth-cars'
    depends_on:
      - cars-shell
    command: |
      bash -c "
        sleep 1
        user-tp -vv -C tcp://validator:4004
      "

  invitations-shell:
    build:
      context: .
      dockerfile: ./shell/invitations/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-invitations-shell
    container_name: invitations-shell
    volumes:
      - .:/project/sawtooth-invitations
      - /project/sawtooth-invitations/client/node_modules
    command: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
          sawtooth keygen
        fi;
        cd client
        npm run-script build
        cd ../
        tail -f /dev/null
      "

  invitations-tp:
    build:
      context: .
      dockerfile: ./processor/invitations_tp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-invitations-tp
    container_name: invitations-tp
    volumes:
      - '.:/project/sawtooth-invitations'
    depends_on:
      - invitations-shell
    command: |
      bash -c "
        sleep 1
        user-tp -vv -C tcp://validator:4004
      "
      
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
